### ISSUE TITLE
I am not able to run the API when compiling against iOS 7.1 base SDK. 

### ISSUE THREAD

**Issue by sgano** [Glympse/glympse-app-sdk#1]
When I envoke '[GlympseLiteWrapper instance].glympse->sendTicket(_glympseTicket, wizardFlags);' 

I am getting a breakpoint (exception) in Thread 1:
it seems to originate from +[NSBundle(glympse) liteBundle]_block_invoke

Anyone else having this issue?

**Comment by glyethan** [comment]
This usually happens if you forget to specify the "-ObjC" flag (no quotes) under "Other linker flags" in your Target's Build Settings. You can take a look at the sample projects for an example of this.

Also, in the future, please direct questions related to Glympse SDK Lite to: http://stackoverflow.com/questions/ask?title=Glympse+API&tags=glympse 

Hope that helps!

**Comment by sgano** [comment]
Thanks for the suggestion but I already do have that flag set; any other possible ideas?

**Comment by sgano** [comment]
Shall I close and move this question over to the "Glympse SDK Lite" section?

**Comment by egorpushkin** [comment]
Yep. Please do. In the meantime we are investigating your issue.
